language: node_js
sudo: required
services:
  - docker
node_js:
  - "node"

before_install:
  - ./install_containers.sh start all

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y jq curl

script:
  - docker ps
  - sleep 3
  - docker logs mean-express
  - docker logs mean-mongo
  - ./scripts/integration_test.sh

notifications:
  email: false
