language: node_js
sudo: required
services:
  - docker
node_js:
  - "node"

before_install:
  - ./install_containers.sh start all

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y jq curl

script:
  - curl -s localhost:3000/get_random_quote | jq -r '.quote.author'
  - docker ps
  - sleep 3
  - ./scripts/integration_test.sh

notifications:
  email: false
