language: node_js
sudo: required
services:
  - docker
node_js:
  - "node"

install:
  - sudo apt-get install jq

script:
  - ./install_containers.sh start all
  - ./scripts/integration_test.sh

notifications:
  email: false
